services:
  database:
    image: mariadb:lts-ubi9
    container_name: database_service
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - app-network
    restart: always

  backend:
    image: eclipse-temurin:21-jdk
    container_name: backend_service
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
    working_dir: /app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./data/backend:/app
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y git maven &&
        git clone --branch ${BRANCH} ${BACKEND_REPO} /tmp/repo &&
        mvn -f /tmp/repo/pom.xml clean package -DskipTests -X &&
        mv /tmp/repo/target/*.jar /app/app.jar &&
        rm -r /tmp/repo
        java -jar /app/app.jar"
    depends_on:
      - database
    networks:
      - app-network
    restart: always

  frontend:
    image: nginx:alpine
    container_name: frontend_service
    working_dir: /app
    command: >
      sh -c "
      apk add --no-cache git nodejs npm &&
      git clone --branch ${BRANCH} ${FRONTEND_REPO} /tmp/repo &&
      cd /tmp/repo &&
      npm install &&
      npm run build &&
      cp -r build /usr/share/nginx/html &&
      rm -r /tmp/repo &&
      nginx -g 'daemon off;'"
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./setting/frontend/nginx-default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  database_data:
